### ISSUE TITLE
Potential bug occurs when Chef server objects deleted

### ISSUE THREAD

**Issue by dblessing** [chef/chef-analytics#13]
I keep encountering an issue where Analytics will suddenly stop displaying any data in the timeline. In `/var/log/opscode-analytics/actions/current` I am seeing the following error:

```
2015-02-13_00:00:08.09527   Entity Load (0.5ms)  SELECT  "entities".* FROM "entities" INNER JOIN "relationships" ON "entities"."id" = "relationships"."entity_id" WHERE "relationships"."relatable_id" = $1 AND "relationships"."relatable_type" = $2 LIMIT 1  [["relatable_id", "294034ba-578b-4790-8acd-dbb10c2b0705"], ["relatable_type", "Entity"]]
2015-02-13_00:00:08.09598 Completed 500 Internal Server Error in 26ms
2015-02-13_00:00:08.09661 ** [Raven] Event not sent due to excluded environment: production
2015-02-13_00:00:08.09853
2015-02-13_00:00:08.09855 Module::DelegationError (Permission#organization delegated to entity.organization, but entity is nil: #<Permission id: "294034ba-578b-4790-8acd-dbb10c2b0705", properties: nil, name: "create", organization_id: "my_org", type: "Permission", search: "'creat':1", metaphone: "KRT">):
2015-02-13_00:00:08.09856   app/models/entities/permission.rb:19:in `rescue in organization'
2015-02-13_00:00:08.09856   app/models/entities/permission.rb:19:in `organization'
2015-02-13_00:00:08.09857   app/models/entity.rb:42:in `manage'
2015-02-13_00:00:08.09857   app/controllers/activities_controller.rb:9:in `index'
2015-02-13_00:00:08.09857
```

I became the `chef-pgsql` user and looked in the `entities` table. I looked for any entry that matched some of the keywords in the error message - namely `metaphone: "KRT"` and the `relatable_id`. What I found was reference to a cookbook I had recently deleted from the server. I went through and deleted this record and one other similar record to a recently deleted cookbook and Analytics suddenly started work.

**Comment by jamesc** [comment]
Thanks for the report.  Had you upgraded any of the components or was this a clean install ?  We had a  bug like this internally before releasing analytics 1.1.0, so I'm wondering if there was perhaps old data sent or is this a different case we didn't catch.  

We should make the organization lookup more robust anyway so you at least can see the valid entries rather than dying completely.

**Comment by dblessing** [comment]
These are clean installs of everything.

**Comment by dblessing** [comment]
In fact, clean installs of Analytics 3 times :smile: It kept happening and I thought it was something I was doing wrong. Then I finally dug in and found the errors and the database records.

**Comment by metadave** [comment]
Related: https://github.com/chef/actions/pull/169

**Comment by PrajaktaPurohit** [comment]
@dblessing it would be awesome if you could help us with some more info. Is this still ongoing issue with analytics? i.e: every time a cookbook is deleted analytics shows a blank page with the "Permission#organization delegated to entity.organization, but entity is nil" error?
To test: 
1) Could you upload a cookbook 
2) Find the relevant entity in the entities table in actions database
3) Delete the cookbook
 4) and check if this entity record (found in step 2) gets deleted after the cookbook is deleted?
Thank you!
