### ISSUE TITLE
Splunk integration: Plain text management port not supported

### ISSUE THREAD

**Issue by surfi2000** [chef/chef-analytics#21]
When disabling SSL on the management port of Splunk, Chef Splunk integration errors out with the following:

2015-04-06_16:03:28.84709 java.lang.RuntimeException: Unrecognized SSL message, plaintext connection?
2015-04-06_16:03:28.84709 	at com.splunk.HttpService.send(HttpService.java:345)
2015-04-06_16:03:28.84709 	at com.splunk.Service.send(Service.java:1278)
2015-04-06_16:03:28.84710 	at com.splunk.HttpService.post(HttpService.java:243)
2015-04-06_16:03:28.84710 	at com.splunk.Service.login(Service.java:1109)
2015-04-06_16:03:28.84710 	at com.splunk.Service.login(Service.java:1089)
2015-04-06_16:03:28.84711 	at com.splunk.Service.connect(Service.java:183)
2015-04-06_16:03:28.84711 	at io.chef.integration.application.Splunk.<init>(Splunk.scala:23)
2015-04-06_16:03:28.84711 	at io.chef.integration.application.Splunk$$anonfun$JSON$1.apply(Splunk.scala:47)
2015-04-06_16:03:28.84711 	at io.chef.integration.application.Splunk$$anonfun$JSON$1.apply(Splunk.scala:47)
2015-04-06_16:03:28.84712 	at argonaut.GeneratedDecodeJsons$$anonfun$jdecode6L$1$$anonfun$apply$289$$anonfun$apply$290$$anonfun$apply$291$$anonfun$apply$292$$anonfun$apply$293$$anonfun$apply$294.apply(GeneratedDecodeJsons.scala:538)
2015-04-06_16:03:28.84712 	at scalaz.$bslash$div$class.map(Either.scala:94)
2015-04-06_16:03:28.84712 	at scalaz.$bslash$div$minus.map(Either.scala:283)
2015-04-06_16:03:28.84713 	at argonaut.DecodeResult.map(DecodeResult.scala:18)
2015-04-06_16:03:28.84713 	at argonaut.GeneratedDecodeJsons$$anonfun$jdecode6L$1$$anonfun$apply$289$$anonfun$apply$290$$anonfun$apply$291$$anonfun$apply$292$$anonfun$apply$293.apply(GeneratedDecodeJsons.scala:537)
2015-04-06_16:03:28.84714 	at argonaut.GeneratedDecodeJsons$$anonfun$jdecode6L$1$$anonfun$apply$289$$anonfun$apply$290$$anonfun$apply$291$$anonfun$apply$292$$anonfun$apply$293.apply(GeneratedDecodeJsons.scala:536)
2015-04-06_16:03:28.84714 	at argonaut.DecodeResult$$anonfun$flatMap$1.apply(DecodeResult.scala:21)
2015-04-06_16:03:28.84714 	at argonaut.DecodeResult$$anonfun$flatMap$1.apply(DecodeResult.scala:21)
2015-04-06_16:03:28.84714 	at scalaz.$bslash$div$class.flatMap(Either.scala:117)
2015-04-06_16:03:28.84715 	at scalaz.$bslash$div$minus.flatMap(Either.scala:283)
2015-04-06_16:03:28.84715 	at argonaut.DecodeResult.flatMap(DecodeResult.scala:21)
2015-04-06_16:03:28.84715 	at argonaut.GeneratedDecodeJsons$$anonfun$jdecode6L$1$$anonfun$apply$289$$anonfun$apply$290$$anonfun$apply$291$$anonfun$apply$292.apply(GeneratedDecodeJsons.scala:536)
2015-04-06_16:03:28.84716 	at argonaut.GeneratedDecodeJsons$$anonfun$jdecode6L$1$$anonfun$apply$289$$anonfun$apply$290$$anonfun$apply$291$$anonfun$apply$292.apply(GeneratedDecodeJsons.scala:535)
2015-04-06_16:03:28.84717 	at argonaut.DecodeResult$$anonfun$flatMap$1.apply(DecodeResult.scala:21)
2015-04-06_16:03:28.84718 	at argonaut.DecodeResult$$anonfun$flatMap$1.apply(DecodeResult.scala:21)
2015-04-06_16:03:28.84718 	at scalaz.$bslash$div$class.flatMap(Either.scala:117)
2015-04-06_16:03:28.84718 	at scalaz.$bslash$div$minus.flatMap(Either.scala:283)
2015-04-06_16:03:28.84718 	at argonaut.DecodeResult.flatMap(DecodeResult.scala:21)
2015-04-06_16:03:28.84719 	at argonaut.GeneratedDecodeJsons$$anonfun$jdecode6L$1$$anonfun$apply$289$$anonfun$apply$290$$anonfun$apply$291.apply(GeneratedDecodeJsons.scala:535)
2015-04-06_16:03:28.84719 	at argonaut.GeneratedDecodeJsons$$anonfun$jdecode6L$1$$anonfun$apply$289$$anonfun$apply$290$$anonfun$apply$291.apply(GeneratedDecodeJsons.scala:534)
2015-04-06_16:03:28.84719 	at argonaut.DecodeResult$$anonfun$flatMap$1.apply(DecodeResult.scala:21)
2015-04-06_16:03:28.84719 	at argonaut.DecodeResult$$anonfun$flatMap$1.apply(DecodeResult.scala:21)
2015-04-06_16:03:28.84720 	at scalaz.$bslash$div$class.flatMap(Either.scala:117)
2015-04-06_16:03:28.84720 	at scalaz.$bslash$div$minus.flatMap(Either.scala:283)
2015-04-06_16:03:28.84720 	at argonaut.DecodeResult.flatMap(DecodeResult.scala:21)
2015-04-06_16:03:28.84721 	at argonaut.GeneratedDecodeJsons$$anonfun$jdecode6L$1$$anonfun$apply$289$$anonfun$apply$290.apply(GeneratedDecodeJsons.scala:534)
2015-04-06_16:03:28.84721 	at argonaut.GeneratedDecodeJsons$$anonfun$jdecode6L$1$$anonfun$apply$289$$anonfun$apply$290.apply(GeneratedDecodeJsons.scala:533)
2015-04-06_16:03:28.84721 	at argonaut.DecodeResult$$anonfun$flatMap$1.apply(DecodeResult.scala:21)
2015-04-06_16:03:28.84721 	at argonaut.DecodeResult$$anonfun$flatMap$1.apply(DecodeResult.scala:21)
2015-04-06_16:03:28.84722 	at scalaz.$bslash$div$class.flatMap(Either.scala:117)
2015-04-06_16:03:28.84722 	at scalaz.$bslash$div$minus.flatMap(Either.scala:283)
2015-04-06_16:03:28.84722 	at argonaut.DecodeResult.flatMap(DecodeResult.scala:21)
2015-04-06_16:03:28.84722 	at argonaut.GeneratedDecodeJsons$$anonfun$jdecode6L$1$$anonfun$apply$289.apply(GeneratedDecodeJsons.scala:533)
2015-04-06_16:03:28.84723 	at argonaut.GeneratedDecodeJsons$$anonfun$jdecode6L$1$$anonfun$apply$289.apply(GeneratedDecodeJsons.scala:532)
2015-04-06_16:03:28.84723 	at argonaut.DecodeResult$$anonfun$flatMap$1.apply(DecodeResult.scala:21)
2015-04-06_16:03:28.84723 	at argonaut.DecodeResult$$anonfun$flatMap$1.apply(DecodeResult.scala:21)
2015-04-06_16:03:28.84723 	at scalaz.$bslash$div$class.flatMap(Either.scala:117)
2015-04-06_16:03:28.84724 	at scalaz.$bslash$div$minus.flatMap(Either.scala:283)
2015-04-06_16:03:28.84724 	at argonaut.DecodeResult.flatMap(DecodeResult.scala:21)
2015-04-06_16:03:28.84724 	at argonaut.GeneratedDecodeJsons$$anonfun$jdecode6L$1.apply(GeneratedDecodeJsons.scala:532)
2015-04-06_16:03:28.84725 	at argonaut.GeneratedDecodeJsons$$anonfun$jdecode6L$1.apply(GeneratedDecodeJsons.scala:531)
2015-04-06_16:03:28.84725 	at argonaut.DecodeJson$$anon$1.decode(DecodeJson.scala:112)
2015-04-06_16:03:28.84725 	at argonaut.GeneratedCodecJsons$$anonfun$casecodec6$3.apply(GeneratedCodecJsons.scala:92)
2015-04-06_16:03:28.84725 	at argonaut.GeneratedCodecJsons$$anonfun$casecodec6$3.apply(GeneratedCodecJsons.scala:92)
2015-04-06_16:03:28.84726 	at argonaut.DecodeJson$$anon$1.decode(DecodeJson.scala:112)
2015-04-06_16:03:28.84726 	at argonaut.CodecJson$class.decode(CodecJson.scala:10)
2015-04-06_16:03:28.84726 	at argonaut.CodecJson$$anon$1.decode(CodecJson.scala:29)
2015-04-06_16:03:28.84726 	at argonaut.DecodeJson$class.apply(DecodeJson.scala:12)
2015-04-06_16:03:28.84727 	at argonaut.CodecJson$$anon$1.apply(CodecJson.scala:29)
2015-04-06_16:03:28.84727 	at argonaut.Json$class.jdecode(Json.scala:403)
2015-04-06_16:03:28.84727 	at argonaut.JObject.jdecode(Json.scala:473)
2015-04-06_16:03:28.84727 	at argonaut.Parse$$anonfun$decode$2.apply(Parse.scala:48)
2015-04-06_16:03:28.84728 	at argonaut.Parse$$anonfun$decode$2.apply(Parse.scala:47)
2015-04-06_16:03:28.84728 	at scalaz.$bslash$div$class.flatMap(Either.scala:117)
2015-04-06_16:03:28.84729 	at scalaz.$bslash$div$minus.flatMap(Either.scala:283)
2015-04-06_16:03:28.84729 	at argonaut.Parse$class.decode(Parse.scala:47)
2015-04-06_16:03:28.84729 	at argonaut.Parse$.decode(Parse.scala:110)
2015-04-06_16:03:28.84729 	at argonaut.Parse$class.decodeOption(Parse.scala:92)
2015-04-06_16:03:28.84730 	at argonaut.Parse$.decodeOption(Parse.scala:110)
2015-04-06_16:03:28.84730 	at io.chef.integration.Main$$anonfun$process$1.apply$mcV$sp(Main.scala:126)
2015-04-06_16:03:28.84730 	at io.chef.integration.Main$$anonfun$process$1.apply(Main.scala:75)
2015-04-06_16:03:28.84730 	at io.chef.integration.Main$$anonfun$process$1.apply(Main.scala:75)
2015-04-06_16:03:28.84731 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
2015-04-06_16:03:28.84731 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
2015-04-06_16:03:28.84731 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
2015-04-06_16:03:28.84731 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)
2015-04-06_16:03:28.84732 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
2015-04-06_16:03:28.84732 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
2015-04-06_16:03:28.84732 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
2015-04-06_16:03:28.84733 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
2015-04-06_16:03:28.84733 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2015-04-06_16:03:28.84733 Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
2015-04-06_16:03:28.84733 	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:671)
2015-04-06_16:03:28.84734 	at sun.security.ssl.InputRecord.read(InputRecord.java:504)
2015-04-06_16:03:28.84734 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:927)
2015-04-06_16:03:28.84734 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
2015-04-06_16:03:28.84734 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
2015-04-06_16:03:28.84735 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
2015-04-06_16:03:28.84735 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:515)
2015-04-06_16:03:28.84735 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
2015-04-06_16:03:28.84735 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1090)
2015-04-06_16:03:28.84736 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
2015-04-06_16:03:28.84736 	at com.splunk.HttpService.send(HttpService.java:338)
2015-04-06_16:03:28.84736 	... 79 more
2015-04-06_16:03:28.84760

**Comment by sersut** [comment]
@surfi2000 I think the root cause of the issues is to enter the management portal port instead of the splunkd port into splunk configuration. By default splunkd port is not SSL-enabled, but management port is. 

We have added more logging into the integration service and we will make a release in the next couple of weeks. Would be great if you can see if this is reproable and what the error messages are with our new release. 

We will announce the new release on our blog when it is out. Thanks for filing this issue and feel free to ping us if you run into something else.
